import { Bar, BarChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import type { SavedCar } from '../types'
import { money, number } from '../utils/format'
import { RiskBadge } from '../components/RiskBadge'

export function Compare({ cars }: { cars: SavedCar[] }) {
  const data = cars.map((car) => ({ name: `${car.brand} ${car.engineId}`, Skóre: car.score, Rezerva: Math.round(car.repairReserve / 1000) }))
  return <>{cars.length ? <><section className="panel chart-panel compare-chart"><div className="panel-head"><div><span className="eyebrow">VIZUÁLNÍ POROVNÁNÍ</span><h2>Skóre a servisní rezerva</h2></div><span className="chart-hint">Rezerva je v tisících Kč</span></div><ResponsiveContainer width="100%" height={340}><BarChart data={data} barGap={4}><CartesianGrid stroke="#273034" vertical={false} /><XAxis dataKey="name" stroke="#7f8b8e" /><YAxis stroke="#7f8b8e" /><Tooltip contentStyle={{ background: '#171d20', border: '1px solid #2a3336', borderRadius: 10 }} /><Legend /><Bar dataKey="Skóre" fill="#b7ff3c" radius={[5,5,0,0]} /><Bar dataKey="Rezerva" fill="#42b8ff" radius={[5,5,0,0]} /></BarChart></ResponsiveContainer></section><section className="panel table-panel"><div className="panel-head"><div><span className="eyebrow">DETAILNÍ DATA</span><h3>Srovnávací tabulka</h3></div></div><div className="table-scroll"><table><thead><tr><th>Vozidlo</th><th>Motor</th><th>Skóre</th><th>Rezerva</th><th>Nájezd</th><th>Stáří</th></tr></thead><tbody>{cars.map((car) => <tr key={car.id}><td><strong>{car.brand}</strong><small>{car.model}</small></td><td>{car.engineId}</td><td><RiskBadge score={car.score} /> <b>{car.score}</b></td><td>{money(car.repairReserve)}</td><td>{number(car.mileage)} km</td><td>{car.age} let</td></tr>)}</tbody></table></div></section></> : <section className="panel empty-state"><span><i className="fa-solid fa-code-compare" /></span><h2>Chybí vozy k porovnání</h2><p>Uložte alespoň dva kandidáty. Porovnání se pak sestaví automaticky.</p></section>}</>
}
